# MultiMovJCommand.msg
# 多关节运动指令消息（话题版本）

int32 robot_id           # LEFT(0), RIGHT(1), DUAL(-1)
MoveMode left_move_mode  # 左臂运动模式
MoveMode right_move_mode # 右臂运动模式
bool is_block            # TRUE(阻塞) 或 FALSE(非阻塞)
JointValue joint_pos_left
JointValue joint_pos_right
float64[] vel            # 2个机器人速度指令
float64[] acc            # 2个机器人加速度指令


# 多关节运动指令消息（话题版本）

int32 robot_id           # LEFT(0), RIGHT(1), DUAL(-1)
MoveMode left_move_mode  # 左臂运动模式
MoveMode right_move_mode # 右臂运动模式
bool is_block            # TRUE(阻塞) 或 FALSE(非阻塞)
JointValue joint_pos_left
JointValue joint_pos_right
float64[] vel            # 2个机器人速度指令
float64[] acc            # 2个机器人加速度指令


# 多关节运动指令消息（话题版本）

int32 robot_id           # LEFT(0), RIGHT(1), DUAL(-1)
MoveMode left_move_mode  # 左臂运动模式
MoveMode right_move_mode # 右臂运动模式
bool is_block            # TRUE(阻塞) 或 FALSE(非阻塞)
JointValue joint_pos_left
JointValue joint_pos_right
float64[] vel            # 2个机器人速度指令
float64[] acc            # 2个机器人加速度指令


# 多关节运动指令消息（话题版本）

int32 robot_id           # LEFT(0), RIGHT(1), DUAL(-1)
MoveMode left_move_mode  # 左臂运动模式
MoveMode right_move_mode # 右臂运动模式
bool is_block            # TRUE(阻塞) 或 FALSE(非阻塞)
JointValue joint_pos_left
JointValue joint_pos_right
float64[] vel            # 2个机器人速度指令
float64[] acc            # 2个机器人加速度指令


# 多关节运动指令消息（话题版本）

int32 robot_id           # LEFT(0), RIGHT(1), DUAL(-1)
MoveMode left_move_mode  # 左臂运动模式
MoveMode right_move_mode # 右臂运动模式
bool is_block            # TRUE(阻塞) 或 FALSE(非阻塞)
JointValue joint_pos_left
JointValue joint_pos_right
float64[] vel            # 2个机器人速度指令
float64[] acc            # 2个机器人加速度指令


# 多关节运动指令消息（话题版本）

int32 robot_id           # LEFT(0), RIGHT(1), DUAL(-1)
MoveMode left_move_mode  # 左臂运动模式
MoveMode right_move_mode # 右臂运动模式
bool is_block            # TRUE(阻塞) 或 FALSE(非阻塞)
JointValue joint_pos_left
JointValue joint_pos_right
float64[] vel            # 2个机器人速度指令
float64[] acc            # 2个机器人加速度指令


# 多关节运动指令消息（话题版本）

int32 robot_id           # LEFT(0), RIGHT(1), DUAL(-1)
MoveMode left_move_mode  # 左臂运动模式
MoveMode right_move_mode # 右臂运动模式
bool is_block            # TRUE(阻塞) 或 FALSE(非阻塞)
JointValue joint_pos_left
JointValue joint_pos_right
float64[] vel            # 2个机器人速度指令
float64[] acc            # 2个机器人加速度指令


# 多关节运动指令消息（话题版本）

int32 robot_id           # LEFT(0), RIGHT(1), DUAL(-1)
MoveMode left_move_mode  # 左臂运动模式
MoveMode right_move_mode # 右臂运动模式
bool is_block            # TRUE(阻塞) 或 FALSE(非阻塞)
JointValue joint_pos_left
JointValue joint_pos_right
float64[] vel            # 2个机器人速度指令
float64[] acc            # 2个机器人加速度指令


# 多关节运动指令消息（话题版本）

int32 robot_id           # LEFT(0), RIGHT(1), DUAL(-1)
MoveMode left_move_mode  # 左臂运动模式
MoveMode right_move_mode # 右臂运动模式
bool is_block            # TRUE(阻塞) 或 FALSE(非阻塞)
JointValue joint_pos_left
JointValue joint_pos_right
float64[] vel            # 2个机器人速度指令
float64[] acc            # 2个机器人加速度指令











